version: '3.7'
services:
  mongodb_container:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 170504
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  app_container:
    build: .
    restart: always
    ports:
      - "8095:8095"
    depends_on:
      - mongodb_container
    links:
      - mongodb_container
volumes:
  mongodb_data_container:
  app_folder_container:
